# Site settings
title: Emersion
email: contact@emersion.fr
description: > # this means to ignore newlines until "baseurl:"
  Site personnel de Emersion
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://emersion.fr" # the base hostname & protocol for your site
twitter_username: emersion_fr
github_username: emersion
deviantart_username: emersion-fr
seenthis_username: emersion

paginate: 5
paginate_path: "/blog/page:num/"

permalink: /blog/:year/:title/

gems: [jekyll-paginate]

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

collections:
    projects_categories:
        output: true
        permalink: /category/:name/

    projects:
        output: true
        permalink: /project/:name/

defaults:
    -
        scope:
            path: ""
            type: projects_categories
        values:
            layout: category
    -
        scope:
            path: ""
            type: projects
        values:
            layout: project
